//
// Created by serik1987 on 18.11.2019.
//

#ifndef MPI2_GLMLAYER_H
#define MPI2_GLMLAYER_H

#include "../../../processors/Processor.h"

namespace net {

    class GlmLayer {
    public:
        /**
         * Creates a certain child mechanism that is constituent of the GLM model
         *
         * @param comm communicator responsible for the mechanism
         * @param mechanism mechanism name (without glm: prefix)
         * @param parameters object generated by the solution method
         * @return instance to the processor
         */
        static equ::Processor* createGlmMechanism(mpi::Communicator& comm, const std::string& mechanism,
                equ::Ode::SolutionParameters parameters);
    };

}


#endif //MPI2_GLMLAYER_H
